"""
Script generator for creating Python scraping scripts

This module generates production-ready Python scripts for web scraping
based on the analysis and selectors discovered by the agent.
"""

import logging
from typing import List, Dict, Literal, Any
from .models import ExtractionPoint

logger = logging.getLogger(__name__)


class ScriptGenerator:
    """
    Generator for Python scraping scripts
    """
    
    def __init__(self):
        """Initialize the script generator"""
        pass
    
    async def generate(self, url: str, extraction_points: List[ExtractionPoint], 
                      selectors: Dict[str, str], method: Literal["http", "browser"],
                      headless: bool = True, wait_for_load: bool = True,
                      ai_improvements: Dict[str, Any] = None) -> str:
        """
        Generate a Python script for web scraping
        
        Args:
            url: URL to scrape
            extraction_points: List of data points to extract
            selectors: CSS selectors for each extraction point
            method: Scraping method (http or browser)
            headless: Whether to run browser in headless mode
            wait_for_load: Whether to wait for page to fully load
            ai_improvements: AI-suggested improvements (optional)
            
        Returns:
            Generated Python script as string
        """
        logger.info(f"Generating {method} script for {len(extraction_points)} extraction points")
        
        if ai_improvements:
            logger.info("Applying AI improvements to script generation")
        
        if method == "http":
            return self._generate_http_script(url, extraction_points, selectors, ai_improvements)
        else:
            return self._generate_browser_script(url, extraction_points, selectors, headless, wait_for_load, ai_improvements)
    
    def _generate_http_script(self, url: str, extraction_points: List[ExtractionPoint], 
                             selectors: Dict[str, str], ai_improvements: Dict[str, Any] = None) -> str:
        """
        Generate script using HTTP requests and BeautifulSoup
        
        Args:
            url: URL to scrape
            extraction_points: List of data points to extract
            selectors: CSS selectors for each extraction point
            
        Returns:
            HTTP-based scraping script
        """
        script_parts = []
        
        # Script header with AI improvements notice
        ai_notice = ""
        if ai_improvements:
            ai_notice = "\n# Enhanced with AI-powered OpenRouter analysis"
        
        script_parts.append(f'''#!/usr/bin/env python3
"""
Auto-generated web scraping script using HTTP requests
Generated by Playwright Agent with OpenRouter AI integration{ai_notice}
"""

import json
import sys
import requests
from bs4 import BeautifulSoup
import re
from typing import Dict, Any, Optional


def extract_data(url: str) -> Dict[str, Any]:
    """
    Extract data from the webpage
    
    Args:
        url: URL to scrape
        
    Returns:
        Dictionary containing extracted data
    """
    # Set up session with headers
    session = requests.Session()
    session.headers.update({{
        'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36'
    }})
    
    try:
        # Make the request
        response = session.get(url, timeout=30)
        response.raise_for_status()
        
        # Parse HTML
        soup = BeautifulSoup(response.content, 'html.parser')
        
        # Extract data
        data = {{}}
''')
        
        # Add extraction logic for each point
        for point in extraction_points:
            selector = selectors.get(point.name)
            if not selector:
                script_parts.append(f'''        
        # {point.name}: No selector found
        data["{point.name}"] = None  # {point.description}
''')
                continue
            
            if point.type == "text":
                script_parts.append(f'''        
        # Extract {point.name}: {point.description}
        try:
            element = soup.select_one("{selector}")
            if element:
                data["{point.name}"] = element.get_text(strip=True)
            else:
                data["{point.name}"] = None
        except Exception as e:
            print(f"Error extracting {point.name}: {{e}}", file=sys.stderr)
            data["{point.name}"] = None
''')
            elif point.type == "number":
                script_parts.append(f'''        
        # Extract {point.name}: {point.description}
        try:
            element = soup.select_one("{selector}")
            if element:
                text = element.get_text(strip=True)
                # Extract number from text
                numbers = re.findall(r'\\\\d+(?:\\\\.\\\\d+)?', text)
                data["{point.name}"] = float(numbers[0]) if numbers else None
            else:
                data["{point.name}"] = None
        except Exception as e:
            print(f"Error extracting {point.name}: {{e}}", file=sys.stderr)
            data["{point.name}"] = None
''')
            elif point.type == "url":
                script_parts.append(f'''        
        # Extract {point.name}: {point.description}
        try:
            element = soup.select_one("{selector}")
            if element:
                # Try to get href attribute first, then text content
                url_value = element.get('href') or element.get_text(strip=True)
                data["{point.name}"] = url_value
            else:
                data["{point.name}"] = None
        except Exception as e:
            print(f"Error extracting {point.name}: {{e}}", file=sys.stderr)
            data["{point.name}"] = None
''')
            elif point.type == "image":
                script_parts.append(f'''        
        # Extract {point.name}: {point.description}
        try:
            element = soup.select_one("{selector}")
            if element:
                # Try to get src attribute
                image_url = element.get('src') or element.get('data-src')
                data["{point.name}"] = image_url
            else:
                data["{point.name}"] = None
        except Exception as e:
            print(f"Error extracting {point.name}: {{e}}", file=sys.stderr)
            data["{point.name}"] = None
''')
            elif point.type == "list":
                script_parts.append(f'''        
        # Extract {point.name}: {point.description}
        try:
            elements = soup.select("{selector}")
            if elements:
                data["{point.name}"] = [elem.get_text(strip=True) for elem in elements]
            else:
                data["{point.name}"] = []
        except Exception as e:
            print(f"Error extracting {point.name}: {{e}}", file=sys.stderr)
            data["{point.name}"] = []
''')
        
        # Script footer
        script_parts.append(f'''        
        return data
        
    except requests.RequestException as e:
        print(f"Request error: {{e}}", file=sys.stderr)
        return {{}}
    except Exception as e:
        print(f"Unexpected error: {{e}}", file=sys.stderr)
        return {{}}


def main():
    """Main execution function"""
    url = "{url}"
    
    # Extract data
    result = extract_data(url)
    
    # Output as JSON
    print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
''')
        
        return ''.join(script_parts)
    
    def _generate_browser_script(self, url: str, extraction_points: List[ExtractionPoint], 
                                selectors: Dict[str, str], headless: bool, wait_for_load: bool,
                                ai_improvements: Dict[str, Any] = None) -> str:
        """
        Generate script using Selenium WebDriver
        
        Args:
            url: URL to scrape
            extraction_points: List of data points to extract
            selectors: CSS selectors for each extraction point
            headless: Whether to run browser in headless mode
            wait_for_load: Whether to wait for page to fully load
            
        Returns:
            Browser-based scraping script
        """
        script_parts = []
        
        # Script header with AI improvements notice
        ai_notice = ""
        if ai_improvements:
            ai_notice = "\n# Enhanced with AI-powered OpenRouter analysis"
        
        headless_str = "True" if headless else "False"
        script_parts.append(f'''#!/usr/bin/env python3
"""
Auto-generated web scraping script using Selenium WebDriver
Generated by Playwright Agent with OpenRouter AI integration{ai_notice}
"""

import json
import sys
import time
import re
from typing import Dict, Any, Optional
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC
from selenium.webdriver.chrome.options import Options
from selenium.common.exceptions import TimeoutException, NoSuchElementException


def setup_driver(headless: bool = {headless_str}) -> webdriver.Chrome:
    """
    Set up Chrome WebDriver with options
    
    Args:
        headless: Whether to run in headless mode
        
    Returns:
        Configured WebDriver instance
    """
    options = Options()
    if headless:
        options.add_argument('--headless')
    options.add_argument('--no-sandbox')
    options.add_argument('--disable-dev-shm-usage')
    options.add_argument('--disable-gpu')
    options.add_argument('--window-size=1920,1080')
    options.add_argument('--user-agent=Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/91.0.4472.124 Safari/537.36')
    
    return webdriver.Chrome(options=options)


def extract_data(url: str) -> Dict[str, Any]:
    """
    Extract data from the webpage using Selenium
    
    Args:
        url: URL to scrape
        
    Returns:
        Dictionary containing extracted data
    """
    driver = None
    
    try:
        # Set up driver
        driver = setup_driver()
        
        # Navigate to page
        driver.get(url)
        
        # Wait for page to load
''')
        
        if wait_for_load:
            script_parts.append('''        time.sleep(3)  # Wait for dynamic content
        
        # Wait for body to be present
        WebDriverWait(driver, 10).until(
            EC.presence_of_element_located((By.TAG_NAME, "body"))
        )
''')
        
        script_parts.append('''        
        # Extract data
        data = {}
''')
        
        # Add extraction logic for each point
        for point in extraction_points:
            selector = selectors.get(point.name)
            if not selector:
                script_parts.append(f'''        
        # {point.name}: No selector found
        data["{point.name}"] = None  # {point.description}
''')
                continue
            
            if point.type == "text":
                script_parts.append(f'''        
        # Extract {point.name}: {point.description}
        try:
            element = driver.find_element(By.CSS_SELECTOR, "{selector}")
            data["{point.name}"] = element.text.strip()
        except NoSuchElementException:
            print(f"Element not found for {point.name}: {selector}", file=sys.stderr)
            data["{point.name}"] = None
        except Exception as e:
            print(f"Error extracting {point.name}: {{e}}", file=sys.stderr)
            data["{point.name}"] = None
''')
            elif point.type == "number":
                script_parts.append(f'''        
        # Extract {point.name}: {point.description}
        try:
            element = driver.find_element(By.CSS_SELECTOR, "{selector}")
            text = element.text.strip()
            # Extract number from text
            numbers = re.findall(r'\\d+(?:\\.\\d+)?', text)
            data["{point.name}"] = float(numbers[0]) if numbers else None
        except NoSuchElementException:
            print(f"Element not found for {point.name}: {selector}", file=sys.stderr)
            data["{point.name}"] = None
        except Exception as e:
            print(f"Error extracting {point.name}: {{e}}", file=sys.stderr)
            data["{point.name}"] = None
''')
            elif point.type == "url":
                script_parts.append(f'''        
        # Extract {point.name}: {point.description}
        try:
            element = driver.find_element(By.CSS_SELECTOR, "{selector}")
            # Try to get href attribute first, then text content
            url_value = element.get_attribute('href') or element.text.strip()
            data["{point.name}"] = url_value
        except NoSuchElementException:
            print(f"Element not found for {point.name}: {selector}", file=sys.stderr)
            data["{point.name}"] = None
        except Exception as e:
            print(f"Error extracting {point.name}: {{e}}", file=sys.stderr)
            data["{point.name}"] = None
''')
            elif point.type == "image":
                script_parts.append(f'''        
        # Extract {point.name}: {point.description}
        try:
            element = driver.find_element(By.CSS_SELECTOR, "{selector}")
            # Try to get src attribute
            image_url = element.get_attribute('src') or element.get_attribute('data-src')
            data["{point.name}"] = image_url
        except NoSuchElementException:
            print(f"Element not found for {point.name}: {selector}", file=sys.stderr)
            data["{point.name}"] = None
        except Exception as e:
            print(f"Error extracting {point.name}: {{e}}", file=sys.stderr)
            data["{point.name}"] = None
''')
            elif point.type == "list":
                script_parts.append(f'''        
        # Extract {point.name}: {point.description}
        try:
            elements = driver.find_elements(By.CSS_SELECTOR, "{selector}")
            data["{point.name}"] = [elem.text.strip() for elem in elements if elem.text.strip()]
        except Exception as e:
            print(f"Error extracting {point.name}: {{e}}", file=sys.stderr)
            data["{point.name}"] = []
''')
        
        # Script footer
        script_parts.append(f'''        
        return data
        
    except Exception as e:
        print(f"Unexpected error: {{e}}", file=sys.stderr)
        return {{}}
    
    finally:
        if driver:
            driver.quit()


def main():
    """Main execution function"""
    url = "{url}"
    
    # Extract data
    result = extract_data(url)
    
    # Output as JSON
    print(json.dumps(result, indent=2, ensure_ascii=False))


if __name__ == "__main__":
    main()
''')
        
        return ''.join(script_parts)